### ISSUE TITLE
Service Monitoring

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-technical-validation#2]
Set-up service uptime monitoring for CSIS internal (Apache, PostGIS) and external services (AIT EMIKAT, ATOS & METEOGRID GeoServer).

**Comment by p-a-s-c-a-l** [comment]
Simple uptime monitoring can already be implemented for
- https://profile.myclimateservices.eu/
- https://csis.myclimateservice.eu/
- https://service.emikat.at/EmiKatTst/api/
- https://service.emikat.at/geoserver/clarity/
- https://geoserver.myclimateservice.eu/geoserver/

**Comment by p-a-s-c-a-l** [comment]
### CSIS PROD
Anonymous access. Check for HTTP Status Code 200

- https://csis.myclimateservice.eu/study/1/step/83/view/summary
- https://csis.ait.ac.at/study/1/step/83/view/summary

**Comment by p-a-s-c-a-l** [comment]
- [ ] **CSIS DEV**
Anonymous access. Check for HTTP Status Code 200

- https://csis-dev.myclimateservice.eu/study/1/step/83/view/summary

**Comment by p-a-s-c-a-l** [comment]
- [ ] **CKAN**
Anonymous access. Check for HTTP Status Code 200

- https://ckan.clarity.cismet.de/organization/activity/clarity/0
- https://ckan.clarity.cismet.de/api/3/action/tag_list
- ~~https://ckan.myclimateservice.eu/~~ (currently not available, see https://github.com/clarity-h2020/ckan/issues/30#issuecomment-584531853)

**Comment by p-a-s-c-a-l** [comment]
Drupal CAS
- [ ] **Drupal CAS**
Anonymous access. Check for HTTP Status Code 200

- https://profile.myclimateservices.eu/cas/login

**Comment by p-a-s-c-a-l** [comment]
- [ ] **Marketplace**
Anonymous access. Check for HTTP Status Code 200

- https://marketplace-dev.myclimateservices.eu/offers
- https://marketplace-dev.myclimateservices.eu/jsonapi

**Comment by p-a-s-c-a-l** [comment]
- [ ] **METEOGRID GeoServer**
Anonymous access. Check for HTTP Status Code 200. Unfortunately, GeoSever still replies with HTTP/200 even when a service exception occurred. 
This service will eventually be shut down, but atm it is still required. See https://github.com/clarity-h2020/ckan/issues/23#issuecomment-584616985

- https://clarity.meteogrid.com/geoserver/ows?service=wms&version=1.1.1&request=GetCapabilities
- https://clarity.meteogrid.com/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3API_consecutive-wet-days_rcp85_20710101-21001231_ensmean&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&maxZoom=undefined&minZoom=undefined&tileSize=1536&attribution=&bbox=1565430.3392804097,4891969.810251283,1682837.6147264405,5009377.085697314
- https://clarity.meteogrid.com/geoserver/europe/wms?&service=WMS&request=GetMap&layers=europe%3API_rr90p_rcp85_20710101-21001231_ensmean&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1565430.3392804097,5009377.085697314,1682837.6147264405,5126784.361143343

**Comment by p-a-s-c-a-l** [comment]
- [ ] **EMIKAT GeoServer**
Anonymous access. Check for HTTP Status Code 200. Unfortunately, GeoServer still replies with HTTP/200 even when a service exception occurred. Moreover, EMIKAT GeoServer delivers an empty image in case of an error. See also https://github.com/clarity-h2020/map-component/issues/80#issuecomment-583992406
- https://service.emikat.at/geoserver/ows?service=wms&version=1.1.1&request=GetCapabilities
- https://service.emikat.at/geoserver/clarity/wms?CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%2720410101-20701231%27%20AND%20EMISSIONS_SCENARIO=%27rcp85%27%20AND%20EVENT_FREQUENCY=%27Occasional%27%20AND%20SZ_ID=3337&&service=WMS&request=GetMap&layers=clarity%3Aview.2974&styles=T_A%0D%0A&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&maxZoom=undefined&minZoom=undefined&tileSize=1536&attribution=&bbox=1271912.150665333,5530371.870489074,1279250.1053807097,5537709.825204453
- https://service.emikat.at/geoserver/clarity/wms?CQL_FILTER=SZ_ID=3232&service=WMS&request=GetMap&layers=clarity%3Aview.2955&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1448023.063834379,5009377.085697314,1565430.3392804097,5126784.361143343

**Comment by p-a-s-c-a-l** [comment]
- [ ] **ATOSGeoServer**
Anonymous access. Check for HTTP Status Code 200. Unfortunately, GeoServer still replies with HTTP/200 even when a service exception occurred. No HTTPS available, see https://github.com/clarity-h2020/csis/issues/120

- http://services.clarity-h2020.eu:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Amortality&bbox=1995203.0178%2C1014243.9784%2C7079558.6386%2C5270223.5146&width=768&height=642&srs=EPSG%3A3035&format=application/openlayers
- http://services.clarity-h2020.eu:8080/geoserver/ows?service=wms&version=1.1.1&request=GetCapabilities
- http://services.clarity-h2020.eu:8080/geoserver/clarity/ows?&service=WMS&request=GetMap&layers=clarity%3Adense_urban_fabric&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&maxZoom=undefined&minZoom=undefined&tileSize=1536&attribution=&bbox=215246.67165105636,5038728.904558817,244598.49051256405,5068080.7234203275

**Comment by p-a-s-c-a-l** [comment]
- [ ] **EMIKKAT REST API**
Basic authentication required. Check for HTTP Status Code 200.

- https://service.emikat.at/EmiKatTst/api/scenarios/3287/feature/tab.CLY_HAZARD_EVENTS_STUDY.2036/table/data?rownum=1000
- https://service.emikat.at/EmiKatTst/api/scenarios/3287/feature/view.2974/table/data?rownum=1000&filter=STUDY_VARIANT%3D%27BASELINE%27&filter=TIME_PERIOD%3D%27Baseline%27&filter=EMISSIONS_SCENARIO%3D%27Baseline%27&filter=EVENT_FREQUENCY%3D%27Rare%27&column=GRID_ID&column=STUDY_VARIANT&column=TIME_PERIOD&column=EMISSIONS_SCENARIO&column=EVENT_FREQUENCY&column=T_MRT&column=T_UTCI&column=T_A&column=DISCOMFORT_LEVEL
- https://service.emikat.at/EmiKatTst/api/scenarios/3287/feature/tab.CLY_EL_POPULATION_INTERPOLATED.2016/table/data?rownum=1000
- https://service.emikat.at/EmiKatTst/api/scenarios/3287/feature/view.2975/table/data?rownum=1000&filter=STUDY_VARIANT%3D%27BASELINE%27&filter=TIME_PERIOD%3D%27Baseline%27&filter=EMISSIONS_SCENARIO%3D%27Baseline%27&filter=EVENT_FREQUENCY%3D%27Rare%27&column=GRID_ID&column=STUDY_VARIANT&column=TIME_PERIOD&column=EMISSIONS_SCENARIO&column=EVENT_FREQUENCY&column=EXPOSEDQUANTITY&column=DAMAGEPROBABILITY&column=DAMAGEQUANTITY
- https://service.emikat.at/EmiKatTst/api/scenarios/3287/feature/view.2975/table/csv?rownum=1000&filter=STUDY_VARIANT%3D%27BASELINE%27&filter=TIME_PERIOD%3D%27Baseline%27&filter=EMISSIONS_SCENARIO%3D%27Baseline%27&filter=EVENT_FREQUENCY%3D%27Rare%27&column=GRID_ID&column=STUDY_VARIANT&column=TIME_PERIOD&column=EMISSIONS_SCENARIO&column=EVENT_FREQUENCY&column=EXPOSEDQUANTITY&column=DAMAGEPROBABILITY&column=DAMAGEQUANTITY
- https://service.emikat.at/EmiKatTst/api/scenarios/3287/feature/view.2994/table/data

**Comment by p-a-s-c-a-l** [comment]
@clarity-ci Statping is now available.

**Comment by p-a-s-c-a-l** [comment]
@jeanatcismet 

Enabling 'Send Updates only' resets the configuration:

![statping](https://user-images.githubusercontent.com/1788226/74350632-44b01b00-4db6-11ea-8d4d-ce41dc625a25.gif)

Can you please restore the correct settings? Maybe a problem with the database volume?

Statping sends weirdly formatted HTML Mails, so we cannot use this feature to update GitHub Issues.

Furthermore, the 'View Service' Link in HTML Mails is missing the domain part: 
```html
<a href=3D"/service/32" class=3D"button button--blue" tar=
get=3D"_blank" style=3D"-webkit-text-size-adjust: none; background: #3869D4=
; border-color: #3869d4; border-radius: 3px; border-style: solid; border-wi=
dth: 10px 18px; box-shadow: 0 2px 3px rgba(0, 0, 0, 0.16); box-sizing: bord=
er-box; color: #FFF; display: inline-block; font-family: Arial, 'Helvetica =
Neue', Helvetica, sans-serif; text-decoration: none;">View Service</a> </td=
>
```
Has the domain name to be configured at the level of the docker-compose file?

**Comment by jeanatcismet** [comment]
> Has the domain name to be configured at the level of the docker-compose file?

No, there is a field for that in the settings. Apparently it has been reseted too.
![Auswahl_126](https://user-images.githubusercontent.com/1787908/74352771-492a0300-4db9-11ea-919f-cc05dd03e7bb.png)

**Comment by jeanatcismet** [comment]
The services from above are now all monitored under https://health-check.clarity.cismet.de/

The Offline/Online status of each service is shown on the front page:

![Auswahl_127](https://user-images.githubusercontent.com/1787908/74354420-9effaa80-4dbb-11ea-83c3-07b7770e611d.png)

Below that, there is on overview of the health history of each service:

![Auswahl_128](https://user-images.githubusercontent.com/1787908/74354462-b048b700-4dbb-11ea-9298-ac3e33b87fd7.png)

Details for each single service can be shown:

![Auswahl_129](https://user-images.githubusercontent.com/1787908/74354514-c6567780-4dbb-11ea-9940-f410e9ab9d11.png)

Inclusively the reason for an offline status:

![Auswahl_130](https://user-images.githubusercontent.com/1787908/74354571-dcfcce80-4dbb-11ea-86aa-fb3bcc020bf1.png)

**Comment by p-a-s-c-a-l** [comment]
> Furthermore, the 'View Service' Link in HTML Mails is missing the domain part

I've created an .env and added DOMAN=https://health-check.clarity.cismet.de/ but that didn't work. Even worse, now all emails are missing the subject:

![grafik](https://user-images.githubusercontent.com/1788226/74409207-8f717780-4e36-11ea-8430-58fac5bc174a.png)

**Comment by p-a-s-c-a-l** [comment]
Still no subject line in emails after removing the .env file. It seems that the configuration (database?) is messed up (again).

**Comment by p-a-s-c-a-l** [comment]
Perhaps we should switch to a tool that is more stable and used in productive environments, e.g. https://cachethq.io/

**Comment by p-a-s-c-a-l** [comment]
> now all emails are missing the subject:

Seems to be related to this setting:

![grafik](https://user-images.githubusercontent.com/1788226/74412582-10803d00-4e3e-11ea-922a-5125f67b4f6c.png)

If the limit is reached, mails will have no subject.

**Comment by p-a-s-c-a-l** [comment]
Now I had to disable email notifications because it's spamming the mailing lists. Apparently, this doesn't work as expected. We should look into an alternative.

**Comment by p-a-s-c-a-l** [comment]
> CSIS (Dev) - Summary (csis-dev.ait.ac.at) is Offline!
> Your Statping service CSIS (Dev) - Summary (csis-dev.ait.ac.at) has been triggered with a HTTP status code of '200' and is currently offline based on your requirements. This failure was created on 2020-02-12 10:56:14.338441671 +0000 UTC.
Last Response
> \<!DOCTYPE html> <html ...

HTTP Status Code is 200 but Statpings sents email notifications, that the service if offline. 😞

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/74419840-c9e50f80-4e4a-11ea-9daf-6bf7d3f3f312.png)

Title & e-mail don’t fit together.

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/74513483-f5c7ca00-4f0a-11ea-9358-459b67acc5f8.png)

Unfortunately, mails are sent every minute when a service is offline, not only when it went offline for the 1st time.

**Comment by p-a-s-c-a-l** [comment]
> Unfortunately, mails are sent every minute when a service is offline, not only when it went offline for the 1st time.

This can be avoided by enabling the "sent updates only" option which is broken atm: https://github.com/clarity-h2020/csis-technical-validation/issues/2#issuecomment-585269169

A patch is available [here](https://github.com/hunterlong/statping/issues/338#issuecomment-585649005) but the PR hasn't been integrated yet.

Unfortunately, this particular setting is not available in .env file or [config.yml](https://github.com/hunterlong/statping/wiki/config.yml), so I've changed the flag directly in the SQLite database:

![grafik](https://user-images.githubusercontent.com/1788226/74523218-f9644c80-4f1c-11ea-9c05-54001e02c378.png)

**Comment by p-a-s-c-a-l** [comment]
Ha-ha, now the subject line is gone [again](https://github.com/clarity-h2020/csis-technical-validation/issues/2#issuecomment-585581019). :hurtrealbad:

**Comment by p-a-s-c-a-l** [comment]
```sh
$ docker-compose start
Starting drupal-db ... done
Starting drupal    ... done
```

>  CKAN - Tag List is Online!
> Your Statping service CKAN - Tag List is back online. This service has been triggered with a HTTP status code of '200' and is currently online based on your requirements. Your service was reported online at 2020-02-11 18:17:19.529653361 +0000 UTC. 

Started CSIS, not CKAN.  Notifications are sent for the wrong service. 🤦‍♂ 
I'll stop wasting my wasting my time with this now.

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/74543237-4a883680-4f45-11ea-8f36-e57bf6cbf6a0.png)

![grafik](https://user-images.githubusercontent.com/1788226/74543358-84f1d380-4f45-11ea-813a-008c0d93c6ad.png)


*lol* 😞

**Comment by p-a-s-c-a-l** [comment]
Temporarily reactivated till #7 is implemented. Dysfunctional mail notifications disabled.
