### ISSUE TITLE
CSIS Acceptance Test by CIS

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-technical-validation#45]
As announced [here](https://github.com/clarity-h2020/csis-technical-validation/issues/1), we now start with the CSIS Acceptance Tests.

Please read the [Acceptance Test Specification](https://github.com/clarity-h2020/csis-technical-validation/wiki/Acceptance-Test-Specification) and follow the 11 steps in the **Walkthrough** section to test the [public BETA of CSIS](https://csis.myclimateservice.eu/).

Please report any problems or bugs according to the instructions in the **Giving Feedback** section.

**Comment by p-a-s-c-a-l** [comment]
@therter Why am I able to see all those cities, even though the HC-LE input data is not available:

![grafik](https://user-images.githubusercontent.com/1788226/83849734-262cb180-a710-11ea-966f-a1cf0f621df0.png)

**Comment by p-a-s-c-a-l** [comment]
Why am I able to see all those studies as 'regular' user:

![grafik](https://user-images.githubusercontent.com/1788226/83844283-fb8a2b00-a706-11ea-86dd-1cbc39c71b0d.png)

See https://github.com/clarity-h2020/docker-drupal/issues/125#issuecomment-639287320

**Comment by p-a-s-c-a-l** [comment]
@therter Can you please tell a a city that's working, I don't want to click on all polygons on [this map](https://geoserver.myclimateservice.eu/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Acity&bbox=1969465.0%2C996016.875%2C7168551.0%2C4677889.0&width=768&height=543&srs=EPSG%3A3035&format=application%2Fopenlayers3)? 
Didn't we have a style for the cities layers so that available cities are shown in a different colour @DanielRodera ?

**Comment by therter** [comment]
> Can you please tell a a city that's working, I don't want to click on all polygons on [this map](https://geoserver.myclimateservice.eu/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Acity&bbox=1969465.0%2C996016.875%2C7168551.0%2C4677889.0&width=768&height=543&srs=EPSG%3A3035&format=application%2Fopenlayers3)?

The following cities should work:

BARI
BOLOGNA
BARCELONA
MADRID
GENOVA
REGGIO_DI_CALABRIA
JELGAVA
HELSINKI
PALERMO
WIEN
TALLINN
SALZBURG
KAUNAS
ATHINA
LINZ
STOCKHOLM
STOKE_ON_TRENT
NAPOLI
GDANSK
ALBA_IULIA

**Comment by p-a-s-c-a-l** [comment]
> There are only two hard things in Computer Science: cache invalidation and **naming things**.
>   -- Phil Karlton

![grafik](https://user-images.githubusercontent.com/1788226/83871566-92b7a880-a730-11ea-87c9-d89c5f04681b.png)

See https://github.com/clarity-h2020/csis/issues/159#issuecomment-639426883

**Comment by p-a-s-c-a-l** [comment]
> Didn't we have a style for the cities layers so that available cities are shown in a different colour @DanielRodera ?

Ah, we can append `&styles=hw_availability` to the URL:

![grafik](https://user-images.githubusercontent.com/1788226/83872875-1a061b80-a733-11ea-9f15-ae3458700371.png)

I've set this as default style for the [cities layer](https://geoserver.myclimateservice.eu/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.resource.ResourceConfigurationPage?8&name=city&wsName=clarity).

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by p-a-s-c-a-l** [comment]
![image](https://user-images.githubusercontent.com/1788226/84262105-4a77fc00-ab1d-11ea-8f21-f0389455ace9.png)

**Comment by p-a-s-c-a-l** [comment]
![image](https://user-images.githubusercontent.com/1788226/84262360-c40fea00-ab1d-11ea-919d-275f365ad8ab.png)
