### ISSUE TITLE
CSIS Acceptance Test by ATOS

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-technical-validation#52]
As announced [here](https://github.com/clarity-h2020/csis-technical-validation/issues/1), we now start with the CSIS Acceptance Tests.

Please read the [Acceptance Test Specification](https://github.com/clarity-h2020/csis-technical-validation/wiki/Acceptance-Test-Specification) and follow the 11 steps in the **Walkthrough** section to test the [public BETA of CSIS](https://csis.myclimateservice.eu/).

Please report any problems or bugs according to the instructions in the **Giving Feedback** section.

If you have further questions regarding the general test process, please contact @therter and @p-a-s-c-a-l 

Initially, it was planned that @DanielRodera and Mario perform the tests. Since Mario isn't avilable any more, I've assigned @maesbri instead. Feel free to ask anybody else from ATOS to perform the tests.

**Comment by DanielRodera** [comment]
Test is done, no bugs to report,

Study: https://csis.myclimateservice.eu/study/161

I created a new user: test1 --> can be deleted

**Comment by p-a-s-c-a-l** [comment]
Thanks!
