### ISSUE TITLE
CSIS Acceptance Test by ZAMG

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-technical-validation#53]
As announced [here](https://github.com/clarity-h2020/csis-technical-validation/issues/1), we now start with the CSIS Acceptance Tests.

Please read the [Acceptance Test Specification](https://github.com/clarity-h2020/csis-technical-validation/wiki/Acceptance-Test-Specification) and follow the 11 steps in the **Walkthrough** section to test the [public BETA of CSIS](https://csis.myclimateservice.eu/).

Please report any problems or bugs according to the instructions in the **Giving Feedback** section.

If you have further questions regarding the general test process, please contact @therter and @p-a-s-c-a-l

**Comment by therter** [comment]
Have you encountered any problems/bugs?

**Comment by claudiahahn** [comment]
Thanks for asking! We did not start checking yet. I hope to that (or at least par of it) tomorrow.

**Comment by claudiahahn** [comment]
https://csis.myclimateservice.eu/study/166/view/context
19.06.2020, 11:15, 
![grafik](https://user-images.githubusercontent.com/45260352/85116875-3ff4eb00-b21e-11ea-9ec7-458fbe5bc892.png)

Not sure if the users understands that he has to edit things here (edit button) in order to go further. It might be helpfull to rename the button maybe to "please enter more information here" or "please select your city here", or anything like that

**Comment by claudiahahn** [comment]
https://csis.myclimateservice.eu/study/166/view/context
https://csis.myclimateservice.eu/study/166/view/context
19.06.2020, 11:19, 
![grafik](https://user-images.githubusercontent.com/45260352/85117235-d75a3e00-b21e-11ea-8550-84c4cbac4fc6.png)
it should be Emmission Scenario: RCP 8.5 (worst case)
now it shows: Emmission Scenario: worst case scenario
But I think Pascal already fixed that in the dev instance?

**Comment by claudiahahn** [comment]
https://csis.myclimateservice.eu/study/166/view/data
19.06.2020, 11:28
![grafik](https://user-images.githubusercontent.com/45260352/85118047-09b86b00-b220-11ea-9a5e-e69604e377de.png)
Shouldn't there be more contributors listed here? 
right now: Denis Havlik and Pascal Dihé

**Comment by claudiahahn** [comment]
ah ok, after selecting the data package all contributors are listed, please ignore my post above

**Comment by claudiahahn** [comment]
https://csis.myclimateservice.eu/group/166/edit/trigger?destination=/study/166/view/summary
19.06.2020, 11:39
![grafik](https://user-images.githubusercontent.com/45260352/85119163-a3344c80-b221-11ea-9dc9-e9292428993d.png)
afer clicking the button to start the calculations, I received the error message

**Comment by claudiahahn** [comment]
but going back and clicking the button again, the calculations started

**Comment by claudiahahn** [comment]
https://csis.myclimateservice.eu/study/166/step/4595/view/table
19.06.2020, 15:50, 
choosing a scenario doesn't really change anything in the table view. -->Select scenario button could be removed? I description explaining what is provided in the table is missing

**Comment by claudiahahn** [comment]
![grafik](https://user-images.githubusercontent.com/45260352/85139498-cc1a0900-b244-11ea-89e9-c7ef65ba7ce4.png)

**Comment by claudiahahn** [comment]
https://csis.myclimateservice.eu/study/166/step/4595/view/maps
19.06.2020,16:04
![grafik](https://user-images.githubusercontent.com/45260352/85141192-ae4da380-b246-11ea-94c8-e4a40c9e1769.png)
tropical nights mean and std should be displayed
map for standard deviation is not shown
only the units are displayed in the legend. It would be very usefull to also display the layer name

**Comment by claudiahahn** [comment]
btw: Firefox 77.0.1 (64-Bit)) Windows10

**Comment by claudiahahn** [comment]
![grafik](https://user-images.githubusercontent.com/45260352/85141583-451a6000-b247-11ea-9508-67c3238b3183.png)

**Comment by claudiahahn** [comment]
![grafik](https://user-images.githubusercontent.com/45260352/85141955-eb666580-b247-11ea-960e-53062ebde067.png)

- the wind indices are under "default"? it should be wind indices or even under the respective wind index
- Also consecutive frost days are listed under consecutive summer days

![grafik](https://user-images.githubusercontent.com/45260352/85142138-31232e00-b248-11ea-83c3-8c17af7d98f7.png)

- the wind indices are all displayed with units "days", even though only for the torro17 index the units are days, for the rest the units should be m/s

**Comment by p-a-s-c-a-l** [comment]
> it should be Emmission Scenario: RCP 8.5 (worst case)
> now it shows: Emmission Scenario: worst case scenario
> But I think Pascal already fixed that in the dev instance?

yes

**Comment by RobAndGo** [comment]
I think **Emissions** Scenario rather than **Emmission** Scenario would make me happier. Note the use of plural Emissions, as can be found [here](https://www.ipcc.ch/report/emissions-scenarios/).

**Comment by claudiahahn** [comment]
sorry, my mistake (also the extra m...). It's correct in CSIS (emissions)

**Comment by p-a-s-c-a-l** [comment]
> I think **Emissions** Scenario rather than **Emmission** Scenario would make me happier. Note the use of plural Emissions, as can be found [here](https://www.ipcc.ch/report/emissions-scenarios/).

In CSIS-DEV ist called **"Emissions Scenario: RCP 8.5 (worst case)"**

> choosing a scenario doesn't really change anything in the table view. -->Select scenario button could be removed? I description explaining what is provided in the table is missing

*Select scenario button* is working now. Table description is now taken from EMIKAT:

![image](https://user-images.githubusercontent.com/1788226/85562622-f3018200-b62c-11ea-950a-ebce026c6ad3.png)

**Comment by p-a-s-c-a-l** [comment]
> after clicking the button to start the calculations, I received the error message

This is being addressed  [here](https://github.com/clarity-h2020/csis/issues/166)

> map for standard deviation is not shown

Hm, perhaps just a temporary error? I'm able to see the layer:
![image](https://user-images.githubusercontent.com/1788226/85563313-8dfa5c00-b62d-11ea-897f-5390d4480650.png)

> only the units are displayed in the legend. It would be very useful to also display the layer name

This is being discussed [here](https://github.com/clarity-h2020/data-package/issues/71)

**Comment by p-a-s-c-a-l** [comment]
> * the wind indices are under "default"? it should be wind indices or even under the respective wind index

done, except for [Wind98p](https://csis-dev.myclimateservice.eu/node/3755). This is being addressed [here](https://github.com/clarity-h2020/docker-drupal/issues/154)

> * Also consecutive frost days are listed under consecutive summer days

done (in CSIS -DEV)

>   *  the wind indices are all displayed with units "days", even though only for the torro17 index the units are days, for the rest the units should be m/s

This is being addressed [here](https://github.com/clarity-h2020/data-package/issues/70)

**Comment by claudiahahn** [comment]
https://csis.myclimateservice.eu/study/166/step/4595/view/maps
hazard characterisation step. 
![grafik](https://user-images.githubusercontent.com/45260352/85863401-64733900-b7c3-11ea-920f-0aaae8873c33.png)

Nothing is displayed (except "Legend") when choosing Urban Atlas 2012 or Urban Atlas 2012 (Building height)

**Comment by claudiahahn** [comment]
https://csis.myclimateservice.eu/study/166/step/4595/view/maps
26.06.2020, 15:44

![grafik](https://user-images.githubusercontent.com/45260352/85863621-b7e58700-b7c3-11ea-80b1-6cc0d7e59fc9.png)
Pascal mentioned in some other issue, that it would be an option to try and get the data and define the color scale --> that would be useful, because now, it is difficult to differentiate between the classes

**Comment by claudiahahn** [comment]
https://csis.myclimateservice.eu/study/166/step/4595/view/maps
hazard characterisation, 26.06.2020, 15:49
![grafik](https://user-images.githubusercontent.com/45260352/85864196-77d2d400-b7c4-11ea-9b20-d12366845cac.png)
legend entries are hard to read

**Comment by claudiahahn** [comment]
https://csis.myclimateservice.eu/study/166/step/4595/view/maps
hazard characterisation, 26.06.2020, 15:51
![grafik](https://user-images.githubusercontent.com/45260352/85864318-ac469000-b7c4-11ea-8901-3185a805ed80.png)
the legend is not good, having blue than purple and then blue again.

**Comment by RobAndGo** [comment]
Maybe the following comment will fit better here. Originally it was posted (via @p-a-s-c-a-l )  [here](https://github.com/clarity-h2020/data-package/issues/73#issuecomment-649437259)

> As I do not know how the colour bar legend is implemented in the map view, I will upload an example of a rather pleasing (to me at least) colour scale which can be used for all heat indices:
[heat_colourbar.rgb.txt](https://github.com/clarity-h2020/csis-technical-validation/files/4838505/heat_colourbar.rgb.txt)
>
>
>It's an ASCII file (remove the temporary .txt extension) and gives the red, green, blue values on a scale from 0-1 for each level. In this case there are 16 colour levels defined (ncolors= 16), and after the comment line (# r g b), the rgb values are defined.
>
>For the cold indices, one would simply need to reverse the order of the colours in the file, which I have done here:
[cold_colourbar.rgb.txt](https://github.com/clarity-h2020/csis-technical-validation/files/4838508/cold_colourbar.rgb.txt)
>
>
>It comes from this website here which has lots of examples of colourbars and their corresponding RGB values.
>
>In general, using stepped rather than continuous colourbars make differences easier to see.
>
>All indices involving precipitation could use this colour scale:
>
>[precip_diff_12lev.rgb.txt](https://github.com/clarity-h2020/csis-technical-validation/files/4838509/precip_diff_12lev.rgb.txt)
>

**Comment by p-a-s-c-a-l** [comment]
Unfortunately, we have no influence on the layers from the groups **Backgrounds**. Of course, those that are based on open data like Corine Land Cover, etc. could be imported in our own GeoServer, but it's up to @DanielRodera @maesbri to decide if they want to take over this task. 

Styling of own layers is discussed [here](https://github.com/clarity-h2020/data-package/issues/73).

**Comment by DanielRodera** [comment]
Hi @p-a-s-c-a-l, I have taken a look with Miguel Angel to the Corine Land Cover layer.

We find out that Copernicus is offering a [WMS endpoint](https://image.discomap.eea.europa.eu/arcgis/services/Corine/CLC2018_WM/MapServer/WMSServer?request=GetCapabilities&service=WMS) for CLC. [Here](https://land.copernicus.eu/pan-european/corine-land-cover/clc2018?tab=mapview) you can find more info.

I guess this layer can be added directly to our CSIS taking advantage they are already serving this dataset for free.

What do you think??

**Comment by p-a-s-c-a-l** [comment]
Thanks @DanielRodera, but it's not about just adding CLC/UA layers available from external services. In fact, all layers in group **Backgrounds** are external layers. It's about the ability to **modify the appearance of these layers** as requested by @claudiahahn [here](https://github.com/clarity-h2020/csis-technical-validation/issues/53#issuecomment-650187689).

That will IMHO only work if the layers are under our full control (managed in our geoserver). But perhaps there is a possibility to change the styles via a `getMap` parameter @therter? But I don't think that we are able to "inject" our own styles. So IMHO our only possibility to download the raw data and serve these layers ourselves.

**Comment by claudiahahn** [comment]
02.07.2020, 10:48
https://csis.myclimateservice.eu/study/113/step/3630/view/maps
![grafik](https://user-images.githubusercontent.com/45260352/86337697-bdbeea80-bc51-11ea-854f-c745e7007907.png)
the background and hazard layers ar not shown in the drop down menu and thus cannot be selected
that problem occured with Firefox 60.0.1 (64-Bit), 
using Chrome (83.0.4103.116) it works, the layers are displayed and can be selected

**Comment by p-a-s-c-a-l** [comment]
Hm, works for me: 
![grafik](https://user-images.githubusercontent.com/1788226/86338750-fd3a0680-bc52-11ea-91aa-622576857bbc.png)



Is there an error on the console? The list of layers is retrieved from the Data Package via CSIS DrupalAPI, so perhaps the problem is on that side. On the other hand, your Firefox is pretty old, the current version is 78.0.1.

**Comment by claudiahahn** [comment]
I guess it's the firefox version ...

**Comment by claudiahahn** [comment]
one can add only 5 study scenarios? 
![grafik](https://user-images.githubusercontent.com/45260352/86340397-1e9bf200-bc55-11ea-92f2-a94db87807cd.png)

**Comment by patrickkaleta** [comment]
> one can add only 5 study scenarios?

Yes, that is currently the limit, which was set this this low on purpose. It's easier to increase that number later on than it is to decrease it (in which case user could potentially lose some of their scenarios if they are above the limit).

Currently we are working on removing the `Study variant` field from the scenarios, which would lead to less scenarios needed by the users.

**Comment by claudiahahn** [comment]
Thanks for the explanation!

**Comment by p-a-s-c-a-l** [comment]
Thanks for testing!
