### ISSUE TITLE
CSIS Acceptance Test by SMHI

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-technical-validation#59]
As announced [here](https://github.com/clarity-h2020/csis-technical-validation/issues/1), we now start the next round of CSIS Acceptance Tests.

Please read the [Acceptance Test Specification](https://github.com/clarity-h2020/csis-technical-validation/wiki/Acceptance-Test-Specification) and follow the 11 steps in the **Walkthrough** section to test the [public BETA of CSIS](https://csis.myclimateservice.eu/).

Please report any problems or bugs according to the instructions in the **Giving Feedback** section.

If you have further questions regarding the general test process, please contact @therter and @p-a-s-c-a-l

**Comment by p-a-s-c-a-l** [comment]
Have you encountered any problems/bugs?

**Comment by yhundecha** [comment]
I couldn't login. Nor could I reset my account. System doesn't recognise my user name. Has any change been made lately that needs us to use a different login credential?

**Comment by patrickkaleta** [comment]
> I couldn't login. Nor could I reset my account. System doesn't recognise my user name. Has any change been made lately that needs us to use a different login credential?

Where did you try to login? Did you use the general `profile.myclimateservices.eu` site (that's the "correct" way to login) or did you try to login directly into the CSIS (https://csis.myclimateservice.eu/)? Try the "reset password" option on the `profile.myclimateservices.eu` site to get a new password.

We had some reports of issues with the login, but that was only for our **development** instance of the CSIS (https://csis-dev.myclimateservice.eu/), which should not be used for the CSIS Acceptance tests.

**Comment by yhundecha** [comment]
Both options do not work for me.

**Comment by patrickkaleta** [comment]
> Both options do not work for me.

Ok, then please try the "reset password" option on the profile.myclimateservices.eu site to get a new password. If that should not work as well, I will manually reset your password and send you a temporary password via e-mail.

**Comment by yhundecha** [comment]
Still doesn't work.

**Comment by patrickkaleta** [comment]
> Still doesn't work.

@fgeyer16 it seems that there is a problem with the "reset password" functionality for the profiles-website. Can you please look into that?

@yhundecha I will reset your password manually and send you further instructions via mail.

**Comment by patrickkaleta** [comment]
@yhundecha  I've reset the password manually and sent out a mail. 

@fgeyer16 I've changed the password for [this user](https://csis.myclimateservice.eu/user/142) directly in the CSIS. Can you please look why this account is having issues with the SSO feature?

**Comment by fgeyer16** [comment]
> Still doesn't work.
The user did not exist on profile.myclimateservices.eu. This was the problem. I created the user on profile.myclimateservices.eu and re enabled SSO for that user.
@yhundecha please login with the login link top right of the homepage of csis. This works now.

**Comment by yhundecha** [comment]
I tried to do the test. All went well, but when I tried to produce a map, it doesn't show any values. It always shows the selected area in two pannels side by side without any values.
![bild](https://user-images.githubusercontent.com/45195885/86771225-24794500-c052-11ea-8ba0-77baea434251.png)

**Comment by p-a-s-c-a-l** [comment]
Thanks. However, I cannot reproduce the problem without further details:

- which layers are selected?
- screenshot of the original map, not the report image
- URL, e. g. https://csis.myclimateservice.eu/study/1/step/83/view/summary
- Browser Version and Operating System, e.g. Firefox 73.0.1 (64-Bit) / Windows 10
- and also the content of the browser console as explained [here](https://github.com/clarity-h2020/csis-technical-validation/wiki/Acceptance-Test-Specification#giving-feedback)

**Comment by yhundecha** [comment]
- Hazard characterization layer is selected
![bild](https://user-images.githubusercontent.com/45195885/86774463-db77bf80-c056-11ea-8840-ec205065ce0e.png)
- https://csis.myclimateservice.eu/study/176/step/4779/view/maps
- Firefox Quantum (Extended support release), 60.1.0esr(32-bits)
- Browser console content:

showing SynchronisedCharacteriseHazardMap for study null (3effa50c-e60d-49c7-923a-998ff8892a2d)
js_BydNlZ78uZyUnwHXPdd1o9lBtxjgWnf6OCqCO4VTBEc.js:205:17
initilizing iFrame with https://csis.myclimateservice.eu/apps/map-component/build/SynchronisedCharacteriseHazardMap/?host=https://csis.myclimateservice.eu&study_uuid=3effa50c-e60d-49c7-923a-998ff8892a2d&study_area=POLYGON((17.901535 59.22768,17.901535 59.367913,18.225632 59.367913,18.225632 59.22768,17.901535 59.22768))&emikat_id=3507&datapackage_uuid=2434ce93-93d4-4ca2-8618-a2de768d3f16&write_permissions=1&study_variant=BASELINE&time_period=20710101-21001231&emissions_scenario=rcp45&event_frequency=Rare&grouping_tag=taxonomy_term--hazards
js_BydNlZ78uZyUnwHXPdd1o9lBtxjgWnf6OCqCO4VTBEc.js:286:13
creating new Hazard Characterization map with layer group from taxonomy_term--hazards and initial bbox POLYGON((17.901535 59.22768,17.901535 59.367913,18.225632 59.367913,18.225632 59.22768,17.901535 59.22768))
BasicMap.js:135:2
rendering two sychronised maps: true
GenericMap.js:66:3
loading data package 2434ce93-93d4-4ca2-8618-a2de768d3f16
BasicMap.js:186:3
fetching datapackage resources from CSIS API:https://csis.myclimateservice.eu/jsonapi/node/data_package/2434ce93-93d4-4ca2-8618-a2de768d3f16/field_resources?include=field_resource_tags,field_references,field_resource_tags.field_var_meaning2
CSISRemoteHelpers.js:141:4
rendering two sychronised maps: true
GenericMap.js:66:3
centering on study area
MapComponent.js:110:4
Map Components synchronised
GenericMap.js:38:3
Minnesförbrukning för Will-change är för hög. Budgetgränsen är dokumentets yta multiplicerat med 3 (603136 pixlar). Förekomster av will-change över budgeten kommer att ignoreras.
SynchronisedCharacteriseHazardMap
process 48 resources and 168 included objects for @mapview:ogc:wms reference type
BasicMap.js:556:2
2 resources left after filtering 48 resources by tag type taxonomy_term--dp_resourcetype and tag name background-layer
CSISHelpers.js:183:2
TypeError: t.relationships.field_references.data.flatMap is not a function[Läs mer]
CSISHelpers.js:313:16
2 resources left after filtering 2 resources by reference type @mapview:ogc:wms
CSISHelpers.js:290:2
2 valid layers for taxonomy_term--dp_resourcetype = background-layer with @mapview:ogc:wms references found in 48 available resources.
BasicMap.js:510:2

**Comment by p-a-s-c-a-l** [comment]
>     * Hazard characterization layer is selected

ok, which Hazard characterization layer exactly does not work? E.g. here I selected the `DI_consecutive-dry-days_ensmean` HC layer:

![image](https://user-images.githubusercontent.com/1788226/86782547-7a081e80-c05f-11ea-9b30-159967bd4bcb.png)

If you don't see the list of layers at all, it's probably related to the `TypeError: t.relationships.field_references.data.flatMap`, which simply  means you browser is too old.  Firefox 60.1.0esr is from May 9, 2018.

**Comment by yhundecha** [comment]
Ok, it looks that the problem is with the browser. I tried chrome and I could see the list of layers.

**Comment by p-a-s-c-a-l** [comment]
Thanks for testing!
