### ISSUE TITLE
CSIS Acceptance Test by WSP

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-technical-validation#60]
As announced [here](https://github.com/clarity-h2020/csis-technical-validation/issues/1), we now start the next round of CSIS Acceptance Tests.

Please read the [Acceptance Test Specification](https://github.com/clarity-h2020/csis-technical-validation/wiki/Acceptance-Test-Specification) and follow the 11 steps in the **Walkthrough** section to test the [public BETA of CSIS](https://csis.myclimateservice.eu/).

Please report any problems or bugs according to the instructions in the **Giving Feedback** section.

If you have further questions regarding the general test process, please contact @therter and @p-a-s-c-a-l

**Comment by p-a-s-c-a-l** [comment]
Have you encountered any problems/bugs?

**Comment by WSPAnna** [comment]
Dear Pascal! Well done, many things looks really nice, I especially like that (during the calculation process) you know how many calculation steps have been finalised. However, I have probably done something wrong, but when I get my PDF, it does not really (from what I find) include any results. I had anticipated for example some maps/tables but am not seing any. But, as I said, I may have missed something. 
[Jkpgfloodtest.pdf](https://github.com/clarity-h2020/csis-technical-validation/files/4874877/Jkpgfloodtest.pdf)

**Comment by p-a-s-c-a-l** [comment]
Yes, the PDF does not include any results of the calculation other than those you add via the **include in report button**.

**Comment by p-a-s-c-a-l** [comment]
Thanks for testing!
