### ISSUE TITLE
CSIS Acceptance Test by CABJOM

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-technical-validation#61]
As announced [here](https://github.com/clarity-h2020/csis-technical-validation/issues/1), we now start the next round of CSIS Acceptance Tests.

Please read the [Acceptance Test Specification](https://github.com/clarity-h2020/csis-technical-validation/wiki/Acceptance-Test-Specification) and follow the 11 steps in the **Walkthrough** section to test the [public BETA of CSIS](https://csis.myclimateservice.eu/).

Please report any problems or bugs according to the instructions in the **Giving Feedback** section.

If you have further questions regarding the general test process, please contact @therter and @p-a-s-c-a-l

**Comment by p-a-s-c-a-l** [comment]
Have you encountered any problems/bugs?

**Comment by manslindell** [comment]
Nope, with only minor test we have to admit….

ml

Best Wishes
Måns Lindell, PhD Limnology
County Administrative Board of Jönköping
S-551 86 Jönköping
Sweden
Phone: +46 10 22 36 408
www.vattern.org<http://www.vattern.org/>
www.lansstyrelsen.se/jonkoping<http://www.lansstyrelsen.se/jonkoping>

Från: Pascal Dihé <notifications@github.com>
Skickat: den 1 juli 2020 11:33
Till: clarity-h2020/csis-technical-validation <csis-technical-validation@noreply.github.com>
Kopia: Lindell Måns <Mans.Lindell@lansstyrelsen.se>; Assign <assign@noreply.github.com>
Ämne: Re: [clarity-h2020/csis-technical-validation] CSIS Acceptance Test by CABJOM (#61)


Have you encountered any problems/bugs?

**Comment by p-a-s-c-a-l** [comment]
Thanks!
