### ISSUE TITLE
How to upload new showcases?

### ISSUE THREAD

**Issue by WSPAnna** [clarity-h2020/csis-technical-validation#63]
Hi! 
I want to add more showcases, as have been performed within DC2, but I do not find where/how to do this. Can anyone give me a clue on how to do this? Best regards, Anna

**Comment by p-a-s-c-a-l** [comment]
This is the latest info I got from @fgeyer16:

> Showcases are/will be synced from Marketplace to CSIS. Patrick and me 
are working on it at the moment.
>
> For every showcase you will have to create a project on marketplace. In 
the Data step of project creation you can add studies to the project in 
which hazards, exposures (elements at risk) and adaption options will be 
added to the project. These three are synced from CSIS to marketplace so 
if something is missing please let me know an I will sync again.
>
>Please note you will have to have an organisation on your profile at 
https://profile.myclimateservices.eu to get onto marketplace. If you 
have done this you will have to wait up to 15 Minutes until the users 
are synced.

So in theory, you should enter your showcases on [marketplace-dev.myclimateservices.eu](https://marketplace-dev.myclimateservices.eu/) (or [marketplace.myclimateservices.eu](https://marketplace.myclimateservices.eu/) once it's available) and then your showcases should also appear on [csis.myclimateservice.eu](https://csis.myclimateservice.eu)❔ and / or csis-dev.myclimateservice.eu](https://csis-dev.myclimateservice.eu)❔. 

But I don't know what the current status is. @fgeyer16 can you please answer that? Are the showcases offered by @mattia-leone now available in CSIS  / Marketplace?

**Comment by p-a-s-c-a-l** [comment]
@martinapizzicato can you please explain here how and where you upload your showcases? Thanks!

**Comment by p-a-s-c-a-l** [comment]
O.K., @WSPAnna, you have to enter the showcases [here](https://csis-dev.myclimateservice.eu/showcases). If you're having trouble logging in into the system, please ask @fgeyer16.

**Comment by martinapizzicato** [comment]
> @martinapizzicato can you please explain here how and where you upload your showcases? Thanks!

Dear @p-a-s-c-a-l 
in https://csis-dev.myclimateservice.eu/ you have to go in "content > add content > showcase. Then in the "create showcase" interface you can upload your data. 
Once you have saved it, it will be available in "showcase"  section.
Contact me if you have any issue.

**Comment by patrickkaleta** [comment]
> > @martinapizzicato can you please explain here how and where you upload your showcases? Thanks!
> 
> Dear @p-a-s-c-a-l
> in https://csis-dev.myclimateservice.eu/ you have to go in "content > add content > showcase. Then in the "create showcase" interface you can upload your data.
> Once you have saved it, it will be available in "showcase" section.
> Contact me if you have any issue.

**One more thing I would like to add:** 
It is important to select a `workflow step` when creating a showcase, so that the CSIS knows in which GL-Step it has to display the new showcase in the Twins tab.
@martinapizzicato you haven't filled out this field, so please do that. I've also now marked this field as a required one, so that this won't happen again in the future.

**Comment by martinapizzicato** [comment]
> > > @martinapizzicato can you please explain here how and where you upload your showcases? Thanks!
> > 
> > 
> > Dear @p-a-s-c-a-l
> > in https://csis-dev.myclimateservice.eu/ you have to go in "content > add content > showcase. Then in the "create showcase" interface you can upload your data.
> > Once you have saved it, it will be available in "showcase" section.
> > Contact me if you have any issue.
> 
> **One more thing I would like to add:**
> It is important to select a `workflow step` when creating a showcase, so that the CSIS knows in which GL-Step it has to display the new showcase in the Twins tab.
> @martinapizzicato you haven't filled out this field, so please do that. I've also now marked this field as a required one, so that this won't happen again in the future.

ok @patrickkaleta i'll fill it for every showcase.

**Comment by patrickkaleta** [comment]
**One more comment:** 

ATM showcases are not part of the content that is synchronized between DEV and PROD (because at the time of configuring the migration files for the individual content types, it was decided that Showcases will primarily reside in the marketplace). 

After today's discussion during our telco, I will now start working on the necessary migration script for Showcases and synchronize them ASAP. So, the showcases you create on the DEV instance will show up in the live CSIS in a couple of days.

**Comment by WSPAnna** [comment]
@manslindell @yhundecha @Stock1Christer @LenaStr FYI, info on how to insert our DC2 Showcases. /Anna

**Comment by WSPAnna** [comment]
@fgeyer16 I'm having some trouble to login. It says (I think) that I need to be a developer to change these things, although as I understand my login is associated with less administrative rights? I am not getting through following the link from Pascal.

**Comment by patrickkaleta** [comment]
> @fgeyer16 I'm having some trouble to login. It says (I think) that I need to be a developer to change these things, although as I understand my login is associated with less administrative rights? I am not getting through following the link from Pascal.

Hi @WSPAnna, I suppose you're talking about login issues on the CSIS DEV instance? We had several issue reports regarding that. I will reset your password on the DEV instance (so for all other CLARITY tools things stay the same) and send you further information via mail.

**Comment by p-a-s-c-a-l** [comment]
@WSPAnna Are you now able to login and create showcases?

**Comment by p-a-s-c-a-l** [comment]
@WSPAnna @manslindell @yhundecha @Stock1Christer @LenaStr FYI @p-a-s-c-a-l martinapizzicato 

As mentioned [here](https://github.com/clarity-h2020/csis/issues/178), showcases have to be created in the **PRODUCTION** instance of CSIS:

In https://csis.myclimateservice.eu/ you have to go in "content > add content > showcase. Then in the "create showcase" interface you can upload your data. Once you have saved it, it will be available in "showcase" section.

**Comment by WSPAnna** [comment]
@patrickkaleta , YES I can login (thanks) but NO I do not manage to add any showcases. I am following the instructions from @p-a-s-c-a-l , but I cannot find "content" anywhere. Where should I look? Thanks for your help guys, I'm feeling like a complete idiot.

**Comment by p-a-s-c-a-l** [comment]
I think the problem is that as non-admin user you don't see this top admin menu:

![image](https://user-images.githubusercontent.com/1788226/88370107-ac20bc80-cd91-11ea-9cb7-97de6feb6e13.png)

So it's definitely not your fault but a usability issue. We should put an 'add showcase' Link on the front page. In the menatime, just use this direct link: https://csis.myclimateservice.eu/node/add/showcase

**Comment by WSPAnna** [comment]
Thanks Pascal. True - I do not see that top admin row. Thanks for the link, I tried submission but failed due to two reasons:
1) I'm having a problem setting the geographical location. The default seems to be Naples (which is nice), but I want them to be Stockholm and Jönköpin grespectively. How do I do that?
2) My company's IT security settings to not permit me to save/upload (see picture, sorry, in Swedish but perhaps you'll get the most important). It says that there is a potential security threat. How can we get around this do you think? Or should I send someone (you?) the info on the showcases so that someone else can upload them?
![bild](https://user-images.githubusercontent.com/45361845/88371244-f014c100-cd93-11ea-9e4f-896f3769e273.png)

**Comment by WSPAnna** [comment]
By the way, it seemt that I can access "content" by looking at the "manage" button top left, then I get the panel of: contrent/structure/configuration/help.

**Comment by patrickkaleta** [comment]
> By the way, it seemt that I can access "content" by looking at the "manage" button top left, then I get the panel of: contrent/structure/configuration/help.

Yes, that's the admin bar [mentioned](https://github.com/clarity-h2020/csis-technical-validation/issues/63#issuecomment-663390974) by Pascal. Even though you are not an administrator, you're an Editor and as such you should have access to that top navigation bar. There under "Content" -> "Add content" -> "Showcase" you should be able to add new showcases.

**Comment by patrickkaleta** [comment]
> Thanks Pascal. True - I do not see that top admin row. Thanks for the link, I tried submission but failed due to two reasons:
> 
> 1. I'm having a problem setting the geographical location. The default seems to be Naples (which is nice), but I want them to be Stockholm and Jönköpin grespectively. How do I do that?

There seems to be a error in the form display. I will fix this, so that a map will be displayed there and then you can simply select the location by clicking on the wished position inside the map.

> 2. My company's IT security settings to not permit me to save/upload (see picture, sorry, in Swedish but perhaps you'll get the most important). It says that there is a potential security threat. How can we get around this do you think? Or should I send someone (you?) the info on the showcases so that someone else can upload them?
>    ![bild](https://user-images.githubusercontent.com/45361845/88371244-f014c100-cd93-11ea-9e4f-896f3769e273.png)

No that error message happened to me as well. Pascal performed a backup of our database, so the system wasn't available for a short period of time. It should now be working again.

**Comment by p-a-s-c-a-l** [comment]
> Pascal performed a backup of our database, so the system wasn't available for a short period of time. It should now be working again.

Yes. Sorry for that inconvenience.

**Comment by patrickkaleta** [comment]
> We should put an 'add showcase' Link on the front page.

Not a bad idea. I won't put it on the front page but instead in the "My content" section of the user profile page.

**Comment by martinapizzicato** [comment]
Hello @patrickkaleta , could you re-authorize me to add showcases? 
The csis give me access denied, I'm using Mattia Leone's account.

**Comment by patrickkaleta** [comment]
> Hello @patrickkaleta , could you re-authorize me to add showcases?
> The csis give me access denied, I'm using Mattia Leone's account.

Hi Martina, you are trying to create showcases on the PROD instance (https://csis.myclimateservice.eu/), correct? It should work there, since Mattia's account has the "Editor" role, which has the permission to create new showcases.

On the DEV instance it is no longer possible to create showcases. (Don't worry, I already moved all the showcases you created there onto the PROD instance.)

**Comment by martinapizzicato** [comment]
ok @patrickkaleta perfect, in PROD instance it works. Thank you!
