### ISSUE TITLE
CSIS Acceptance Test by the Municipality of Linz

### ISSUE THREAD

**Issue by johanneshorak** [clarity-h2020/csis-technical-validation#76]
https://csis.myclimateservice.eu/study/185/view/team
2020-07-13 14:30
Firefox 78.0.1 (64-Bit) / Windows 10

![grafik](https://user-images.githubusercontent.com/18684786/87306364-30fd1200-c518-11ea-950a-e02fdc57a8c0.png)

**expected behaviour:**
The walkthrough #3 required me to add another member from my organisation with the role team to the study. As we didn't have another user I created a second user account. The user creation worked as far as I can tell and I was able to log in with the new user (maglinztest) in a separate Browser (I used MS Edge for this). With my main user (johanneshorak) I then opened the study and clicked on "Team" where I clicked on "Add member". There's a search field here where I would have expected to find the newly created user.,

**actual behaviour:**
However, the user did not show up when searching for it. I tried searching for the user name (maglinztest) in total and for parts of it (mag, linz, test). I tried searching for the last and first name I entered for that user, to no avail. After a couple of attempts and waiting for a while I quit for a couple of hours and when I came back to it, I was able to find the user by entering its user name (it actually popped up as a suggestion after having typed "mag").

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 I think this is the expected behaviour, isn't it? :-) User synchronisation from .profiles to .csis takes some time.

**Comment by johanneshorak** [comment]
I was thinking that it might just take some time to synchronize and it's probably not really a use case anyone else but a tester will encounter. Still, I thought it would be worth to at least mention it :)

**Comment by johanneshorak** [comment]
https://csis.myclimateservice.eu/study/185/step/5119/view/summary
2020-07-13 14:30
Firefox 78.0.1 (64-Bit) / Windows 10

![grafik](https://user-images.githubusercontent.com/18684786/87314616-cbaf1e00-c523-11ea-9244-bd4bc04b6e0b.png)

**expected behaviour** I was expecting to see a full map in the OpenStreetMap Panel.
**actual behavour** Most tiles in the map were not loaded. I just noticed the map only completes when I open up the console window with CTRL+SHIFT+I. I can actually reproduce this. Pressing F5 results again in the incomplete map. Opening the console completes it.
**what i did** I followed all the steps to create a study and was in the process of clicking through HC, HCLE, EE, VA,... and the respective subitems (introduction, data, table). After clicking on summary and scrolling down a bit to "Included Elements" and expanding "Details" of "DC3 - Climate adaption for the city of Linz" the above is what I see. Refreshing did not load the missing tiles.

**Comment by johanneshorak** [comment]
https://csis.myclimateservice.eu/study/185/step/5120/view/data
2020-07-13 14:30
Firefox 78.0.1 (64-Bit) / Windows 10

![grafik](https://user-images.githubusercontent.com/18684786/87316245-d2d72b80-c525-11ea-8072-c227cc193c52.png)

I'll just stick with the proposed structure of these posts even though it looks a little bit funny with these short remarks :)

**expected behaviour:**: I would expect text without html tags.
**actual behaviour**: I do see html tags.
**steps to reproduce**: I selected Hazard Characterization - Local Effects and there the sub item "Data". All data packages (local effect apparent temperature, local effect mean radiant temperature and local effect UTCI temperature) have html tags. In their description.

**Comment by johanneshorak** [comment]
https://csis.myclimateservice.eu/study/185/step/5120/view/table
2020-07-13 16:39
Firefox 78.0.1 (64-Bit) / Windows 10

![grafik](https://user-images.githubusercontent.com/18684786/87317599-84c32780-c527-11ea-8acb-9cc990ef315d.png)

a really minor issue here, might come down to personal preference

**expected behaviour**: Table description should read "The table lists mean-, UTCI (Universal Thermal Climate Index)- and Apperent Temperature and Discomfort level for **the selected** RCP Scenarios."
**actual behaviour**: Table description does read "The table lists mean-, UTCI (Universal Thermal Climate Index)- and Apperent Temperature and Discomfort level for **different** RCP Scenarios."

bold to emphasize the part I'm referring to.

**Comment by johanneshorak** [comment]
https://csis.myclimateservice.eu/study/185/step/5121/view/twins
2020-07-13 16:59
Firefox 78.0.1 (64-Bit) / Windows 10

![grafik](https://user-images.githubusercontent.com/18684786/87319627-28add280-c52a-11ea-8d65-779ae3d1d1f5.png)

**expected behaviour**: map panel should load correctly
**actual behaviour**: Google maps pop up indicates some problem loading the map. "For development purposes only" is printed all over the map.
**steps to reproduce**: I selected "Exposure Evaluation" and the subitem "Twins" there. The problem appeared immediately and neither refreshing nor choosing other menu items first got rid of it.

**Comment by johanneshorak** [comment]
https://csis.myclimateservice.eu/study/185/step/5122/view/data
and
https://csis.myclimateservice.eu/study/185/step/5122/view/table
2020-07-13 17:05
Firefox 78.0.1 (64-Bit) / Windows 10

![grafik](https://user-images.githubusercontent.com/18684786/87320400-2ef07e80-c52b-11ea-9205-b6f7094e2d1a.png)

![grafik](https://user-images.githubusercontent.com/18684786/87320438-3a43aa00-c52b-11ea-858e-a3bcb3a6289d.png)

**expected behaviour**: Since there's no data set listed when I click on subitem "Data" I would expect there to be no Table nor a Summary,
**actual behaviour**: There are results but there is no data? Maybe I misunderstand what I'm being shown here.
**steps to reproduce**: I selected "Vulnerability Analysis" and the subitems "Data" and "Table".

**Comment by johanneshorak** [comment]
https://csis.myclimateservice.eu/study/185
2020-07-13 17:28
Firefox 78.0.1 (64-Bit) / Windows 10

![grafik](https://user-images.githubusercontent.com/18684786/87321754-ecc83c80-c52c-11ea-846c-6d44129438a1.png)

**expected behaviour**: I expected a download of the PDF report to start
**actual behaviour**: The error message in the screenshot popped up.
**steps to reproduce**: I can't really say I know what contributed to the crash. That would need me redoing all the previous steps in the walkthrough to see if some of the information I entered in the text fields was the problem or if the problem lies somewhere else.

**Comment by fgeyer16** [comment]
> @fgeyer16 I think this is the expected behaviour, isn't it? :-) User synchronisation from .profiles to .csis takes some time.

CSIS is using the "old" way: SSO user will be generated on their first log in. So maglinztest should have been available after his first login. Since maglinztest was able to login synchronisation should have worked and the user should have been selectable/findable.
