### ISSUE TITLE
CSIS Acceptance Test by EUREKA

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-technical-validation#80]
As announced [here](https://github.com/clarity-h2020/csis-technical-validation/issues/1), we now start with the CSIS Acceptance Tests.

Please read the [Acceptance Test Specification](https://github.com/clarity-h2020/csis-technical-validation/wiki/Acceptance-Test-Specification) and follow the 11 steps in the **Walkthrough** section to test the [public BETA of CSIS](https://csis.myclimateservice.eu/).

Please report any problems or bugs according to the instructions in the **Giving Feedback** section.

If you have further questions regarding the general test process, please contact @therter and @p-a-s-c-a-l

**Comment by Mauro-Iorio** [comment]
Point 3 Add another team member ........
In a not recorded test, I have asked Fabiola Labia to register on CSIS.
I had to wait the next day to be able to find and add her as team member of the study.

**Comment by Mauro-Iorio** [comment]
After the end of the Step 8, I have tried to press the "Download this report as PDF" in the Study Report section.

https://csis.myclimateservice.eu/study/187/view/summary
Date & Time, 2020-07-25 19:20:00
Google Chrome Versione 84.0.4147.89 (Build ufficiale) (a 64 bit) / Windows 10 Version 1909 per x64
Screenshot before:
![Annotazione 2020-07-25 192718](https://user-images.githubusercontent.com/45432235/88462611-f6e32700-ceac-11ea-9e16-cc341667aefd.png)
Screenshot after:
![Annotazione 2020-07-25 193114](https://user-images.githubusercontent.com/45432235/88462670-7a9d1380-cead-11ea-8c2d-6566ef325403.png)

**Comment by p-a-s-c-a-l** [comment]
Thank you @Mauro-Iorio ! I've resolved the problem, PDF download is working now.

**Comment by Mauro-Iorio** [comment]
General Comment: 
Step 5 - I have created two study scenarios.
Step 9 - For HC, HC-LE and HC-EE, there is no reported (printed) correlation, in the "summary sections" as well as in the "Study Report", between each "study scenario" and the related maps and tables.
Please see my report in the section HC: i have tried to report the correlation in the titles of maps and tables.

**Comment by Mauro-Iorio** [comment]
Date & Time, 2020-07-31 12:00:00
Google Chrome Versione 84.0.4147.89 (Build ufficiale) (a 64 bit) / Windows 10 Version 1909 per x64

Step 9, HC Table section.
https://csis.myclimateservice.eu/study/187/step/5204/view/table

Screenshot:
![Cattura3](https://user-images.githubusercontent.com/45432235/89023407-d17a7100-d323-11ea-8b82-620dba44661a.JPG)

Download of csv format
![Cattura4](https://user-images.githubusercontent.com/45432235/89023712-49489b80-d324-11ea-9cb4-4f48e2a53893.JPG)

There is a problem on the Latitude and Longitude format (a dot more).

**Comment by Mauro-Iorio** [comment]
Date & Time, 2020-07-31 12:00:00
Google Chrome Versione 84.0.4147.89 (Build ufficiale) (a 64 bit) / Windows 10 Version 1909 per x64

Step 9, HC-LE Table section.
https://csis.myclimateservice.eu/study/187/step/5205/view/table

Screenshot:
![Cattura6](https://user-images.githubusercontent.com/45432235/89025035-6f6f3b00-d326-11ea-9176-49ccd7419fc3.JPG)


Download of csv format
![Cattura5](https://user-images.githubusercontent.com/45432235/89024590-a3962c00-d325-11ea-86b5-3811c6be4118.JPG)

There are many problems: mismatch of the headers and wrong formats (i.e. Temperatures).

**Comment by Mauro-Iorio** [comment]
Date & Time, 2020-07-31 12:20:00
Google Chrome Versione 84.0.4147.89 (Build ufficiale) (a 64 bit) / Windows 10 Version 1909 per x64

Step 9, RA/IA Table section.
https://csis.myclimateservice.eu/study/187/step/5208/view/table

Screenshot:
![Cattura7](https://user-images.githubusercontent.com/45432235/89026101-5e272e00-d328-11ea-99be-0aacb65397fb.JPG)

Download of csv format
![Cattura8](https://user-images.githubusercontent.com/45432235/89026276-b1997c00-d328-11ea-9f1a-cb16eec156aa.JPG)

There are many problems of wrong format:
HW_DAMAGEPROBABILITY
HW_DAMAGEQUANTITY
PF_RESIDENTIAL_BUILDINGS
PF_NON_RESIDENTIAL_BUILDINGS
PF_ROADS_M2
PF_FLOOD_IMPACT_EURO

SZM_SZENARIO_REF shloud be SZM_SCENARIO_REF ?

**Comment by p-a-s-c-a-l** [comment]
> There is a problem on the Latitude and Longitude format (a dot more).

That's just a problem of Microsoft Excel. This is the raw data downloaded from EMIKAT:

```CSV
Latitude;Longitude;Hazard Event Type;EMISSIONS_SCENARIO;TIME_PERIOD;EVENT_FREQUENCY;Event Descriptor;Temp95Perz
40.833246;14.281113;HW;rcp45;20110101-20401231;Frequent;34.5_3.033d;31.6
40.833246;14.281113;RAIN;rcp45;20110101-20401231;Frequent;85;
```

**Comment by p-a-s-c-a-l** [comment]
> There are many problems: mismatch of the headers and wrong formats (i.e. Temperatures).

@humerh  Can you please have a look?

**Comment by humerh** [comment]
In this case CSV format is provided.
CSV does not provide additional info about character encoding and  national encoding for decimal and group seperators.

Excel can open .csv files, but normally uses the default setting of the country, where Excel is called.
If you have international setting, than "40.833246" will be interpreted correctly.
If you have (as example) a German setting, then the '.' will be interpreted as a group seperator and the result will be "40.833.246".
But this is the internal behavior of Excel, I can do nothing against this. 
You have to change the setting of Excel.
